CRM/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.EventsListView.as_view(), name='dashboard'),
    path('ajax-search/', views.ajax_search, name='ajax_search'),
    path('notifications/', views.notifications, name='notifications'),
    path('mark-notification-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('mark-all-notifications-as-read/', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('create_client/', views.create_client, name='create_client'),
    path('events_list/', views.EventsListView.as_view(), name='events_list'),
    path('get_locations/', views.GetLocationsView.as_view(), name='get_locations'),
    path('get_properties/', views.GetProperties.as_view(), name='get_properties'),
    path('get_event_types/', views.GetEventTypes.as_view(), name='get_event_types'),
    path('get_clients/', views.GetClients.as_view(), name='get_clients'),
    path('get_events/', views.get_events, name='get_events'),
    path('add_property/', views.add_property, name='add_property'),
    path('add_rental_property/', views.add_rental_property, name='add_rental_property'),
    path('events/add/', views.add_event, name='add_event'),
    path('events/edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('events/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('events/toggle_complete/<int:event_id>/', views.toggle_complete, name='toggle_complete'),
    path('events/add_event_type/', views.add_event_type, name='add_event_type'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/<int:client_id>/', views.client_events, name='client_events'),
    path('clients/edit/<int:client_id>/', views.edit_client, name='edit_client'),
    path('clients/delete/<int:client_id>/', views.delete_client, name='delete_client'),
    path('clients/add_notes/<int:client_id>/', views.add_client_notes, name='add_client_notes'),
    path('clients/update_suggestion/', views.suggest_property, name='update_suggestion'),
    path('events/delete_notes/<int:note_id>/<int:client_id>/', views.delete_client_note, name='delete_notes'),
    path('properties/', views.properties_list, name='properties_list'),
    path('properties/<int:property_id>/', views.property_events, name='property_events'),
    path('properties/edit/<int:property_id>/', views.edit_property, name='edit_property'),
    path('properties/delete/<int:property_id>/', views.delete_property, name='delete_property'),
    path('search/', views.search_page, name='search_page'),
    path('google-maps-script/', views.google_maps_proxy, name='google_maps_proxy'),
    path('delete_image/<int:photo_id>/', views.delete_image, name='delete_image'),
    
    path('settings_page/',views.settings_page, name='settings'),
    path('settings_page/google-authenticate/', views.google_authenticate, name='google_authenticate'),
    path('settings_page/google-authenticate-callback/', views.google_authenticate_callback, name='google_authenticate_callback'),
    path('settings_page/import-google-contacts/', views.import_google_contacts, name='import_google_contacts'),
    path('settings_page/event_types_list/', views.event_types_list, name='event_types_list'),
    path('settings_page/edit_event_type/<int:event_type_id>/', views.edit_event_type, name='edit_event_type'),
    path('settings_page/delete_event_type/<int:event_type_id>/', views.delete_event_type, name='delete_event_type'),
    path('settings_page/client_status_list/', views.client_status_list, name='client_status_list'),
    path('settings_page/edit_client_status/<int:client_status_id>/', views.edit_client_status, name='edit_client_status'),
    path('settings_page/add_client_status/', views.add_client_status, name='add_client_status'),
    path('settings_page/delete_client_status/<int:client_status_id>/', views.delete_client_status, name='delete_client_status'),
    path('settings_page/property_status_list/', views.property_status_list, name='property_status_list'),
    path('settings_page/edit_property_status/<int:property_status_id>/', views.edit_property_status, name='edit_property_status'),
    path('settings_page/add_property_status/', views.add_property_status, name='add_property_status'),
    path('settings_page/delete_property_status/<int:property_status_id>/', views.delete_property_status, name='delete_property_status'),
    path('settings_page/property_type_list/', views.property_type_list, name='property_type_list'),
    path('settings_page/edit_property_type/<int:property_type_id>/', views.edit_property_type, name='edit_property_type'),
    path('settings_page/add_property_type/', views.add_property_type, name='add_property_type'),
    path('settings_page/delete_property_type/<int:property_type_id>/', views.delete_property_type, name='delete_property_type'),
    path('settings_page/property_deal_type_list/', views.property_deal_type_list, name='property_deal_type_list'),
    path('settings_page/edit_property_deal_type/<int:property_deal_type_id>/', views.edit_property_deal_type, name='edit_property_deal_type'),
    path('settings_page/add_property_deal_type/', views.add_property_deal_type, name='add_property_deal_type'),
    path('settings_page/delete_property_deal_type/<int:property_deal_type_id>/', views.delete_property_deal_type, name='delete_property_deal_type'),
    path('settings_page/suggestions_link_settings/', views.suggestions_link_settings_page, name='suggestions_link_settings'),
    path('settings_page/profile/', views.profile, name='profile'),
    path('settings_page/products', views.products, name = 'subscriptions'),
    path('settings_page/checkout', views.checkout_monthly, name = 'checkout_monthly'),
    path('settings_page/checkout_yearly', views.checkout_yearly, name = 'checkout_yearly'),
    path('settings_page/subscriptions/succeeded', views.payment_successful, name = 'payment_successful'),
    path('settings_page/subscriptions/succeeded_y', views.payment_successful_yearly, name = 'payment_successful_yearly'),
    path('settings_page/subscriptions/cancelled', views.payment_cancelled, name = 'payment_cancelled'),
]

Realtor/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('client_resources/', views.client_resources, name='client_resources'),
    path('properties/', views.properties, name='properties'),
    path('buy_properties/', views.buy_properties, name='buy_properties'),
    path('buy_properties/<int:id>/',views.detail_view, name='detail'),
    path('rent_properties/', views.rent_properties, name='rent_properties'),
    path('rent_properties/<int:id>/',views.detail_view_rental, name='detail_view_rental'),
    path('to_rent_properties/', views.to_rent_properties, name='to_rent_properties'),
    path('sell_properties/', views.sell_properties, name='sell_properties'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import user_login
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/',include('CRM.urls')),
    path('card/', include('suggest_properties.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', user_login, name='user_login'),
    
    path('reset_password/', 
        auth_views.PasswordResetView.as_view(
             template_name = 'reset_password.html'), 
            name='reset_password'),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'reset_password_sent.html'), 
            name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'reset.html'), 
            name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'password_reset_complete.html'), 
            name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Realtor/models.py
from django.db import models
from accounts.models import CustomUser

class LinkModel(models.Model):
    url = models.URLField()
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.description

class property_status(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='crm_property_statuses')
    status = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.status}"
    
class property_type(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='crm_property_types')
    type = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.type}"
    
class deal_type(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='crm_property_deal_types')
    deal_type = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.deal_type}"

class Property(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    property_type = models.ForeignKey(property_type,max_length=20, blank=True, null = True, on_delete=models.CASCADE, related_name = 'property_types')
    deal_type = models.ForeignKey(deal_type,max_length=10, blank=True, null = True, on_delete=models.CASCADE, related_name = 'property_deal_type')
    address = models.CharField(max_length=255, blank=True, null = True)
    images = models.ImageField(blank=True, null=True)
    sqr_meter = models.IntegerField(blank=True, null = True)
    price_sqrm = models.FloatField(null=True, blank = True)
    price_month = models.CharField(null=True, blank = True, max_length = 30)
    condition = models.CharField(max_length=20, blank=True, null = True)
    address_lower = models.CharField(max_length=255, blank=True, null = True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    listing_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    lot_size = models.IntegerField(null=True, blank=True)
    monthly_fees = models.IntegerField(null=True, blank=True)
    year_built = models.IntegerField(null=True, blank=True)
    unit = models.CharField(max_length=20, blank=True, null=True)
    status = models.ForeignKey(property_status,max_length=30,blank=True, null= True, on_delete=models.CASCADE,related_name= 'property_status_type')

    bedrooms = models.IntegerField(blank=True, null = True)
    total_rooms = models.IntegerField(blank=True, null = True)
    toilets = models.IntegerField(blank=True, null = True)
    garage = models.IntegerField(blank=True, null = True)
    fireplace = models.IntegerField(blank=True, null = True)
    dining_room = models.IntegerField(blank=True, null = True)
    living_room = models.IntegerField(blank=True, null = True)
    school_distance = models.IntegerField(blank=True, null = True)

    total_floor = models.IntegerField(blank=True, null = True)
    which_floor = models.IntegerField(blank=True, null = True)
    year_built = models.IntegerField(null=True, blank=True)

    description = models.TextField(blank=True, null = True)
    dining_room_description = models.TextField(blank=True, null = True)
    living_room_description = models.TextField(blank=True, null = True)
    interior_features_description = models.TextField(blank=True, null = True)
    exterior_features_description = models.TextField(blank=True, null = True)
    style_description = models.TextField(blank=True, null = True)
    design_description = models.TextField(blank=True, null = True)
    extra_notes = models.TextField(blank=True, null = True)

    postal_code = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    sub_district = models.CharField(max_length=255, blank=True, null=True)
    total_price = models.CharField(max_length=255, blank=True, null=True)
    added_date = models.DateTimeField(auto_now_add=True, blank= True,null=True)
    views_count = models.IntegerField(default=0)
    def save(self, *args, **kwargs):
        if self.address:
            self.address = self.address.replace("/", "")
        # Save the lowercase version of the address
        self.address_lower = self.address.lower()
        super().save(*args, **kwargs)

    
    @property
    def name(self):
        if self.total_price:
            return f"{self.address} - {self.total_price}"
        else:
            return self.address

    def __str__(self):
        return self.name
            
    
class PropertyImage(models.Model):
    property = models.ForeignKey('Property', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='property_images/')

    def __str__(self):
        return f"{self.property.deal_type} - {self.property.address}"

Realtor/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import LinkModel, Property, PropertyImage
# Create your views here.

def home(request):
    
    return render(request, 'home.html')

def about(request):
    return render(request, "about.html")

def properties(request):
    return render(request, "properties.html")

def services(request):
    # Fetch links from the database
    links = LinkModel.objects.all()

    # Pass links to the template
    context = {'links': links}
    return render(request, "services.html", context)

def client_resources(request):
    return render(request, "client_resources.html")

def rent_properties(request):
    properties_for_rent = Property.objects.filter(deal_type='rental')
    # Get filter values from the request
    property_type_filter = request.GET.get('property_type', '')
    availability_filter = request.GET.get('availability', '')
    condition_filter = request.GET.get('condition', '')
    search_query = request.GET.get('search', '')
    search_query = search_query.lower()

    # Apply filters if values are provided
    if property_type_filter:
        properties_for_rent = properties_for_rent.filter(property_type=property_type_filter)
    if availability_filter:
        properties_for_rent = properties_for_rent.filter(availability=availability_filter)
    if condition_filter:
        properties_for_rent = properties_for_rent.filter(condition=condition_filter)
    if search_query:
        # Use case-insensitive search by comparing lowercase values
        properties_for_rent = properties_for_rent.filter(address_lower__icontains=search_query)

    return render(
        request,
        'rent_properties.html',
        {
            'propertys': properties_for_rent,
            'property_type_filter': property_type_filter,
            'availability_filter': availability_filter,
            'condition_filter': condition_filter,
            'search_query': search_query,
        }
    )

def to_rent_properties(request):
    return render(request, 'to_rent_properties.html')

def sell_properties(request):
    return render(request, "sell_properties.html")
def buy_properties(request):
    properties_for_sale = Property.objects.filter(deal_type='selling')

    # Get filter values from the request
    property_type_filter = request.GET.get('property_type', '')
    availability_filter = request.GET.get('availability', '')
    condition_filter = request.GET.get('condition', '')
    search_query = request.GET.get('search', '')
    search_query = search_query.lower()

    # Apply filters if values are provided
    if property_type_filter:
        properties_for_sale = properties_for_sale.filter(property_type=property_type_filter)
    if availability_filter:
        properties_for_sale = properties_for_sale.filter(availability=availability_filter)
    if condition_filter:
        properties_for_sale = properties_for_sale.filter(condition=condition_filter)
    if search_query:
        # Use case-insensitive search by comparing lowercase values
        properties_for_sale = properties_for_sale.filter(address_lower__icontains=search_query)

    return render(
        request,
        'buy_properties.html',
        {
            'propertys': properties_for_sale,
            'property_type_filter': property_type_filter,
            'availability_filter': availability_filter,
            'condition_filter': condition_filter,
            'search_query': search_query,
        }
    )
def detail_view(request, id):
    property = get_object_or_404(Property, id=id)
    photos = PropertyImage.objects.filter(property=property)
    return render(request, 'details.html', {
        'properties':property,
        'photos':photos
    })

def detail_view_rental(request, id):
    property = get_object_or_404(Property, id=id)
    photos = PropertyImage.objects.filter(property=property)
    return render(request, 'detailsRental.html', {
        'properties':property,
        'photos':photos
    })

Realtor/templates/about.html
{% extends "base.html" %} 
{% block title %} Бидний тухай {% endblock %}
{% block body_class %}
<p>About</p>
{% endblock %}

Realtor/templates/buy_properties.html
{% extends 'base.html' %}

{% block body_class %}
<style>
    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        padding-top: 80px;
        width: 90%;
        padding-left: 10%;
    }

    /* Individual card styles */
    .col {
        width: 30%; /* Adjust the width as needed */
        margin-bottom: 20px; /* Adjust the margin as needed */
    }
    /* Media query for smaller screens */
    @media (max-width: 900px) {
        .col {
            width: 45%; /* Adjust the width for 2 columns on smaller screens */
        }
    }

    .card {
        border: 1px solid #ddd;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card:hover {
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .card-img-top {
        width: 100%;
        height: auto;
        transition: transform 0.3s ease-in-out; /* Transition effect for zoom-in */
    }

    .card:hover .card-img-top {
        transform: scale(1.1); /* Zoom in on hover */
    }

    .card-body {
        padding: 15px;
    }

    .card-title {
        font-size: 1.25rem;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 1rem;
        color: #000;
        margin-bottom: 15px;
    }

    .card-body p {
      font-size: 0.8rem;
      color: grey;
    }

    .card-body p {
        margin: 0; /* Remove the default margin for <p> elements */
        display: flex;
        align-items: center; /* Align items vertically */
    }

    .card-body i {
        margin-right: 5px; /* Adjust the spacing between icon and text */
    }


    .btn-md {
        padding: 10px 20px;
        font-size: 1rem;
    }
    .filters-section {

        margin-top: 80px;
        display: flex;
        flex-wrap:wrap;
        align-items: center;
        width: 80%;
        margin-left: 10%;
    }

    .filter-select{
        margin: 10px;
        padding: 8px;
        font-size: 1rem;
    }

    .filter-button {
        padding: 8px 16px;
        font-size: 1rem;
    }

    .filters-section input {
        padding-left: 10px;
    }

    .search-bar {
        width: 200px; /* Adjust the width as needed */
        margin: 10px;
        padding: 8px;
        right: 10%;
        font-size: 1rem;
    }
</style>

<!-- Filters -->
<form action="{% url 'buy_properties' %}" method="get" class="filters-section">

    <!-- Property Type Filter -->
    <select class="filter-select" name="property_type" id="propertyTypeFilter">
        <option value="" {% if not property_type_filter %}selected{% endif %}>All Types</option>
        <option value="house" {% if property_type_filter == 'house' %}selected{% endif %}>House</option>
        <option value="apartment" {% if property_type_filter == 'apartment' %}selected{% endif %}>Apartment</option>
        <!-- Add more options as needed -->
    </select>

    <!-- Availability Filter -->
    <select class="filter-select" name="availability" id="availabilityFilter">
        <option value="">All Availabilities</option>
        <option value="available">Available</option>
        <option value="occupied">Occupied</option>
        <!-- Add more options as needed -->
    </select>

    <!-- Condition Filter -->
    <select class="filter-select" name="condition" id="conditionFilter">
        <option value="">All Conditions</option>
        <option value="good">Good</option>
        <option value="fair">Fair</option>
        <!-- Add more options as needed -->
    </select>
    <!-- Search Bar -->
    <button type="submit" class="filter-button">Apply Filters</button>

    <input type="text" name="search" placeholder="Хайх" value="{{ request.GET.search }}" class="search-bar">

    <!-- Add more filters as needed -->

</form>



<div class="row row-cols-1 row-cols-lg-3">
    {% for property in propertys %}
    <a href="{% url 'detail' property.id %}">
        <div class="col mb-4">
            <div class="card">
                <div class="view overlay">
                    <img class="card-img-top" src="{{ property.images.url }}" alt="">
                    <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
                <div class="card-body">
                    <h2 class="card-text">{{ property.address }}</h2>
                    <p><i class="material-icons">bed</i> Унтлаганы өрөө: {{ property.bedrooms }}</p>
                    <p><i class="material-icons">home</i> Мкв: {{ property.sqr_meter }}</p>
                    <p><i class="material-icons">attach_money</i> Мкв - ийн үнэ: {{ property.price_sqrm }} сая</p>
                    <p><i class="material-icons">attach_money</i> Нийт үнэ: {{ property.total_price }} сая</p>
                    <p><i class="material-icons">handshake</i> Нөхцөл : {{ property.get_condition_display }}</p>
                </div>
                
            </div>
        </div>
    </a>
    {% endfor %}
  </div>

{% endblock %}

Realtor/templates/client_resources.html
{% extends "base.html" %} 
{% block title %} Realtor Gunbadrakh {% endblock %}
{% block body_class %}
<p>Client Resource</p>
{% endblock %}

Realtor/templates/properties.html
{% extends "base.html" %} 
{% block title %} Estates Solutions {% endblock %}
{% block body_class %}
<p>Properties</p>
{% endblock %}

Realtor/templates/rent_properties.html
{% extends 'base.html' %}

{% block body_class %}
<style>
    .row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        padding-top: 80px;
        width: 90%;
        padding-left: 10%;
    }

    /* Individual card styles */
    .col {
        width: 30%; /* Adjust the width as needed */
        margin-bottom: 20px; /* Adjust the margin as needed */
    }
    /* Media query for smaller screens */
    @media (max-width: 900px) {
        .col {
            width: 45%; /* Adjust the width for 2 columns on smaller screens */
        }
    }

    .card {
        border: 1px solid #ddd;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card:hover {
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .card-img-top {
        width: 100%;
        height: auto;
        transition: transform 0.3s ease-in-out; /* Transition effect for zoom-in */
    }

    .card:hover .card-img-top {
        transform: scale(1.1); /* Zoom in on hover */
    }

    .card-body {
        padding: 15px;
    }

    .card-title {
        font-size: 1.25rem;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 1rem;
        color: #000;
        margin-bottom: 15px;
    }

    .card-body p {
      font-size: 0.8rem;
      color: grey;
    }

    .card-body p {
        margin: 0; /* Remove the default margin for <p> elements */
        display: flex;
        align-items: center; /* Align items vertically */
    }

    .card-body i {
        margin-right: 5px; /* Adjust the spacing between icon and text */
    }


    .btn-md {
        padding: 10px 20px;
        font-size: 1rem;
    }
    .filters-section {

        margin-top: 80px;
        display: flex;
        flex-wrap:wrap;
        align-items: center;
        width: 80%;
        margin-left: 10%;
    }

    .filter-select{
        margin: 10px;
        padding: 8px;
        font-size: 1rem;
    }

    .filter-button {
        padding: 8px 16px;
        font-size: 1rem;
    }

    .filters-section input {
        padding-left: 10px;
    }

    .search-bar {
        width: 200px; /* Adjust the width as needed */
        margin: 10px;
        padding: 8px;
        right: 10%;
        font-size: 1rem;
    }
</style>

<!-- Filters -->
<form action="{% url 'buy_properties' %}" method="get" class="filters-section">

    <!-- Property Type Filter -->
    <select class="filter-select" name="property_type" id="propertyTypeFilter">
        <option value="" {% if not property_type_filter %}selected{% endif %}>All Types</option>
        <option value="house" {% if property_type_filter == 'house' %}selected{% endif %}>House</option>
        <option value="apartment" {% if property_type_filter == 'apartment' %}selected{% endif %}>Apartment</option>
        <!-- Add more options as needed -->
    </select>

    <!-- Availability Filter -->
    <select class="filter-select" name="availability" id="availabilityFilter">
        <option value="">All Availabilities</option>
        <option value="available">Available</option>
        <option value="occupied">Occupied</option>
        <!-- Add more options as needed -->
    </select>

    <!-- Condition Filter -->
    <select class="filter-select" name="condition" id="conditionFilter">
        <option value="">All Conditions</option>
        <option value="good">Good</option>
        <option value="fair">Fair</option>
        <!-- Add more options as needed -->
    </select>
    <!-- Search Bar -->
    <button type="submit" class="filter-button">Apply Filters</button>

    <input type="text" name="search" placeholder="Хайх" value="{{ request.GET.search }}" class="search-bar">

    <!-- Add more filters as needed -->

</form>


<div class="row row-cols-1 row-cols-md-3">
    {% for property in propertys %}
    <a href="{% url 'detail_view_rental' property.id %}">
        <div class="col mb-4">
            <div class="card">
                <div class="view overlay">
                    <img class="card-img-top" src="{{ property.images.url }}" alt="">
                    <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>
                <div class="card-body">
                    <h2 class="card-text">{{ property.address }}</h2>
                    <p><i class="material-icons">bed</i> Унтлаганы өрөө: {{ property.bedrooms }}</p>
                    <p><i class="material-icons">home</i> Мкв: {{ property.sqr_meter }}</p>
                    <p><i class="material-icons">attach_money</i> Мкв - ийн үнэ: {{ property.price_month }}</p>
                    <p><i class="material-icons">handshake</i> Нөхцөл : {{ property.get_condition_display  }}</p>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}
  </div>
{% endblock %}

Realtor/templates/sell_properties.html
{% extends "base.html" %} 
{% block title %} Estates Solutions {% endblock %}
{% block body_class %}
<p>Sell Properties</p>
{% endblock %}

Realtor/templates/services.html
{% extends "base.html" %} 
{% block title %} Estates Solutions {% endblock %}
{% block body_class %}
{% load static %}
<p>Services</p>

<style>
     /* Container for Facebook Reels */
     .reels-container {
        display: flex;
        overflow-x: auto; /* Use auto to display a scrollbar if needed */
        white-space: nowrap;
        padding: 20px; /* Optional: Add padding to the container */
        justify-content: center; /* Center align the videos */
    }

    /* Individual Reel Item */
    .reel-item {
        flex: 0 0 auto;
        margin-right: 10px; /* Adjust the spacing between videos */
        cursor: pointer;
    }

    /* Styling for the Facebook Embedded Video Player */
    iframe {
        width: 267px;
        height: 476px;
        border: none;
        overflow: hidden;
        display: flex; /* Initially hide all videos */
        transition: transform 0.3s ease; /* Add a smooth transition effect */
    }

    /* Optional: Add hover effect for better user experience */
    .reel-item:hover {
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    /* Center align and make the selected video bigger */
    .reel-item.selected iframe {
        transform: scale(1.5); /* Adjust the scale factor as needed */
        z-index: 1; /* Ensure the selected video is on top */
    }
</style>

<div class="reels-container">
    {% for link in links %}
    <div class="reel-item">
        <iframe src="{{ link.url }}" width="267" height="476" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe>
    </div>
    {% endfor %}
</div>
<script>
    
</script>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v10.0" nonce="your_nonce"></script>
{% endblock %}

Realtor/templates/to_rent_properties.html
{% extends "base.html" %} 
{% block title %} Estates Solutions {% endblock %}
{% block body_class %}
<p>To Rent Properties</p>
{% endblock %}