CRM/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.EventsListView.as_view(), name='dashboard'),
    path('ajax-search/', views.ajax_search, name='ajax_search'),
    path('notifications/', views.notifications, name='notifications'),
    path('mark-notification-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('mark-all-notifications-as-read/', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('create_client/', views.create_client, name='create_client'),
    path('events_list/', views.EventsListView.as_view(), name='events_list'),
    path('get_locations/', views.GetLocationsView.as_view(), name='get_locations'),
    path('get_properties/', views.GetProperties.as_view(), name='get_properties'),
    path('get_event_types/', views.GetEventTypes.as_view(), name='get_event_types'),
    path('get_clients/', views.GetClients.as_view(), name='get_clients'),
    path('get_events/', views.get_events, name='get_events'),
    path('add_property/', views.add_property, name='add_property'),
    path('add_rental_property/', views.add_rental_property, name='add_rental_property'),
    path('events/add/', views.add_event, name='add_event'),
    path('events/edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('events/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('events/toggle_complete/<int:event_id>/', views.toggle_complete, name='toggle_complete'),
    path('events/add_event_type/', views.add_event_type, name='add_event_type'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/<int:client_id>/', views.client_events, name='client_events'),
    path('clients/edit/<int:client_id>/', views.edit_client, name='edit_client'),
    path('clients/delete/<int:client_id>/', views.delete_client, name='delete_client'),
    path('clients/add_notes/<int:client_id>/', views.add_client_notes, name='add_client_notes'),
    path('clients/update_suggestion/', views.suggest_property, name='update_suggestion'),
    path('events/delete_notes/<int:note_id>/<int:client_id>/', views.delete_client_note, name='delete_notes'),
    path('properties/', views.properties_list, name='properties_list'),
    path('properties/<int:property_id>/', views.property_events, name='property_events'),
    path('properties/edit/<int:property_id>/', views.edit_property, name='edit_property'),
    path('properties/delete/<int:property_id>/', views.delete_property, name='delete_property'),
    path('search/', views.search_page, name='search_page'),
    path('google-maps-script/', views.google_maps_proxy, name='google_maps_proxy'),
    path('delete_image/<int:photo_id>/', views.delete_image, name='delete_image'),
    
    path('settings_page/',views.settings_page, name='settings'),
    path('settings_page/google-authenticate/', views.google_authenticate, name='google_authenticate'),
    path('settings_page/google-authenticate-callback/', views.google_authenticate_callback, name='google_authenticate_callback'),
    path('settings_page/import-google-contacts/', views.import_google_contacts, name='import_google_contacts'),
    path('settings_page/event_types_list/', views.event_types_list, name='event_types_list'),
    path('settings_page/edit_event_type/<int:event_type_id>/', views.edit_event_type, name='edit_event_type'),
    path('settings_page/delete_event_type/<int:event_type_id>/', views.delete_event_type, name='delete_event_type'),
    path('settings_page/client_status_list/', views.client_status_list, name='client_status_list'),
    path('settings_page/edit_client_status/<int:client_status_id>/', views.edit_client_status, name='edit_client_status'),
    path('settings_page/add_client_status/', views.add_client_status, name='add_client_status'),
    path('settings_page/delete_client_status/<int:client_status_id>/', views.delete_client_status, name='delete_client_status'),
    path('settings_page/property_status_list/', views.property_status_list, name='property_status_list'),
    path('settings_page/edit_property_status/<int:property_status_id>/', views.edit_property_status, name='edit_property_status'),
    path('settings_page/add_property_status/', views.add_property_status, name='add_property_status'),
    path('settings_page/delete_property_status/<int:property_status_id>/', views.delete_property_status, name='delete_property_status'),
    path('settings_page/property_type_list/', views.property_type_list, name='property_type_list'),
    path('settings_page/edit_property_type/<int:property_type_id>/', views.edit_property_type, name='edit_property_type'),
    path('settings_page/add_property_type/', views.add_property_type, name='add_property_type'),
    path('settings_page/delete_property_type/<int:property_type_id>/', views.delete_property_type, name='delete_property_type'),
    path('settings_page/property_deal_type_list/', views.property_deal_type_list, name='property_deal_type_list'),
    path('settings_page/edit_property_deal_type/<int:property_deal_type_id>/', views.edit_property_deal_type, name='edit_property_deal_type'),
    path('settings_page/add_property_deal_type/', views.add_property_deal_type, name='add_property_deal_type'),
    path('settings_page/delete_property_deal_type/<int:property_deal_type_id>/', views.delete_property_deal_type, name='delete_property_deal_type'),
    path('settings_page/suggestions_link_settings/', views.suggestions_link_settings_page, name='suggestions_link_settings'),
    path('settings_page/profile/', views.profile, name='profile'),
    path('settings_page/products', views.products, name = 'subscriptions'),
    path('settings_page/checkout', views.checkout_monthly, name = 'checkout_monthly'),
    path('settings_page/checkout_yearly', views.checkout_yearly, name = 'checkout_yearly'),
    path('settings_page/subscriptions/succeeded', views.payment_successful, name = 'payment_successful'),
    path('settings_page/subscriptions/succeeded_y', views.payment_successful_yearly, name = 'payment_successful_yearly'),
    path('settings_page/subscriptions/cancelled', views.payment_cancelled, name = 'payment_cancelled'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import user_login
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/',include('CRM.urls')),
    path('card/', include('suggest_properties.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', user_login, name='user_login'),
    
    path('reset_password/', 
        auth_views.PasswordResetView.as_view(
             template_name = 'reset_password.html'), 
            name='reset_password'),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'reset_password_sent.html'), 
            name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'reset.html'), 
            name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'password_reset_complete.html'), 
            name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CRM/models.py
from django.db import models
from Realtor.models import Property
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
from accounts.models import CustomUser
from django.utils import timezone
from django.db.models.signals import pre_save
import datetime

class client_status_types(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.CharField(max_length = 255)

    def __str__(self):
        return f"{self.status}"
    


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

class Clent(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    client_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=30,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    link = models.CharField(max_length=8, unique=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    wedding_anniversary = models.DateField(null=True, blank=True)
    home_anniversary = models.DateField(null=True, blank=True)
    facebook_url = models.URLField(null=True, blank=True)
    instagram_url = models.URLField(null=True, blank=True)
    twitter_url = models.URLField(null=True, blank=True)
    linkedin_url = models.URLField(null=True, blank=True)
    google_resource_id = models.CharField(null=True,blank = True, max_length= 255)
  
    status = models.ForeignKey(client_status_types, max_length=50, null=True, blank=True, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.client_name} - {self.phone_number} - {self.email}"

    def save(self, *args, **kwargs):
        if not self.link:
            self.link = self.generate_unique_id()
        super().save(*args, **kwargs)

        # Check if the status has changed
        if self.pk is not None:
            old_instance = Clent.objects.get(pk=self.pk)
            if old_instance.status != self.status:
                self.last_status_change = timezone.now()
                self.previous_status = old_instance.status

                # Create a StatusChangeLog entry
                StatusChangeLog.objects.create(
                    clent=self,
                    changed_date=self.last_status_change,
                    previous_status=self.previous_status,
                    new_status=self.status
                )

    def generate_unique_id(self):
        unique_id = str(uuid.uuid4().hex)[:8]
        while Clent.objects.filter(link=unique_id).exists():
            unique_id = str(uuid.uuid4().hex)[:8]
        return unique_id
    
    @property
    def name(self):
        if self.phone_number:
            return f"{self.client_name} - {self.phone_number}"
        else:
            return self.client_name

    def __str__(self):
        return self.name

class client_relationships(models.Model):
    user = models.ForeignKey(Clent,on_delete=models.CASCADE)
    relationship_choices = (
        ('husband', 'Husband'),
        ('wife', 'Wife'),
        ('son', 'Son'),
        ('daughter', 'Daughter'),
        ('friend', 'Friend'),
        ('colleague', 'Colleague'),
        ('other', 'Other'),
    )
    name = models.CharField(max_length=255, null=True,blank=True)
    phone_number = models.CharField(max_length=30,null=True,blank=True)
    relationship_type = models.CharField(choices=relationship_choices, max_length = 255)

    def __str__(self):
        return f"{self.user} - {self.phone_number} - {self.name}- {self.relationship_type}"

class client_phone_numbers(models.Model):
    user = models.ForeignKey(Clent, on_delete = models.CASCADE)
    phone_types_choices = (
        ('work', 'Work'),
        ('home', 'Home'),
        ('mobile', 'Mobile'),
        ('fax', 'Fax'),
        ('other', 'Other'),
    )
    phone_type = models.CharField(choices = phone_types_choices, max_length = 255)
    phone_number = models.CharField(max_length=16) 
    def __str__(self):
        return f"{self.user} - {self.phone_type} - {self.phone_number}"

class StatusChangeLog(models.Model):
    client = models.ForeignKey(Clent, on_delete=models.CASCADE)
    changed_date = models.DateTimeField()
    previous_status = models.CharField(max_length=50)
    new_status = models.CharField(max_length=50)

class Client_suggestion(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    client = models.ForeignKey(Clent, on_delete=models.CASCADE, related_name='client_suggestions')    
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='property_suggestions')  
    SUGGESTION_CHOICES = (
        ('suggested', 'SUGGESTED'),
        ('not_suggested', 'NOT SUGGESTED')
    )
    INTERESTED_CHOICES = (
        ('interested', 'INTERESTED'),
        ('not_interested', 'NOT INTERESTED')
    )
    is_suggested = models.CharField(default="not_suggested", choices=SUGGESTION_CHOICES, max_length=50)
    is_interested = models.CharField(default='not_interested', choices=INTERESTED_CHOICES, max_length=50)

    def client_link(self):
        return self.client.link

    def __str__(self):
        return f"{self.client} - {self.property} - {self.is_suggested} - {self.is_interested} - {self.client_link()}"

class event_type_model(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    event_type = models.CharField(max_length = 255)

    def __str__(self):
        return f"{self.event_type}"

class Event(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    event_hour_choice = (
        ('01','01'),
        ('02','02'),
        ('03','03'),
        ('04','04'),
        ('05','05'),
        ('06','06'),
        ('07','07'),
        ('08','08'),
        ('09','09'),
        ('10','10'),
        ('11','11'),
        ('12','12'),
    )
    event_minute_choice = (
        ('00','00'),
        ('15','15'),
        ('30','30'),
        ('45','45'),
    )
    event_ampm_choice = (
        ('am','AM'),
        ('pm','PM'),
    )

    
    event_type = models.ForeignKey(event_type_model,max_length=255, null=True, blank=True,on_delete = models.DO_NOTHING, related_name = 'events_types')
    event_date = models.DateField()
    event_hour = models.CharField(null=True, blank=True, max_length = 5, choices = event_hour_choice)
    event_minute = models.CharField(null=True, blank=True, max_length = 5, choices = event_minute_choice)
    event_ampm = models.CharField(null=True, blank=True, max_length = 5, choices = event_ampm_choice)
    participant_buyer = models.ForeignKey(Clent, on_delete=models.CASCADE, related_name='events_bought', null=True,blank=True)
    participant_owner = models.ForeignKey(Clent, on_delete=models.CASCADE, related_name='events_owned', null=True,blank=True)
    event_description = models.TextField(null=True,blank=True)
    participant_property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='events_property', null=True,blank=True)
    is_completed = models.BooleanField(default = False) 
    participant_owner_name = models.CharField(max_length=255, null=True, blank=True, editable=False)
    participant_buyer_name = models.CharField(max_length=255, null=True, blank=True, editable=False)
    participant_property_address = models.CharField(max_length=255, null=True, blank=True, editable=False)
    participant_property_images = models.CharField(max_length=255, null=True, blank=True, editable=False)
    event_type_name = models.CharField(max_length=255, null=True, blank=True, editable=False)
    index_field = models.DateTimeField(blank=True, null=True, editable=False)

    def save(self, *args, **kwargs):
        # Convert date, hour, minute, am/pm to a datetime object
        if self.event_type:
            self.event_type_name = self.event_type.event_type

        # Save participant_owner's client name
        if self.participant_owner:
            self.participant_owner_name = self.participant_owner.client_name

        # Save participant_buyer's client name
        if self.participant_buyer:
            self.participant_buyer_name = self.participant_buyer.client_name

        if self.participant_property:
            self.participant_property_address = self.participant_property.address
            try:
                self.participant_property_images = self.participant_property.images.url
            except:
                pass


        if self.event_date:
            hour = int(self.event_hour) if self.event_hour else 0
            minute = int(self.event_minute) if self.event_minute else 0
            am_pm = self.event_ampm if self.event_ampm else 'AM'

            if am_pm.upper() == 'PM' and hour != 12:
                hour += 12

            index_field_value = datetime.datetime.combine(self.event_date, datetime.time(hour, minute))
            self.index_field = index_field_value

        super().save(*args, **kwargs)

    @property
    def locations(self):
        if self.participant_property:
            return {
                'latitude': self.participant_property.latitude,
                'longitude': self.participant_property.longitude,
                'id': self.participant_property.id,
            }
        else:
            return None

    def __str__(self):
        return f"{self.event_type} - {self.event_date} - {self.participant_buyer} - {self.participant_owner}"

class Files(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    file = models.FileField(upload_to='property_images/')

    def __str__(self):
        return f"{self.property} - {self.file}"

@receiver(post_save, sender=Clent)
def create_client_suggestions(sender, instance, created, **kwargs):
    if created:
        properties = Property.objects.filter(user=instance.user)
        for property in properties:

CRM/templates/delete_client_status.html
{% extends 'base_event.html' %}

{% block title %}Estates Solutions | Delete Client Status{% endblock %}

{% block content %}
<h2 class="container-header">Delete Client Status</h2>
  <div class="container-content">

    <p>Are you sure you want to delete the status "{{ event_type.event_type }}"?</p>

    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>

    <a href="{% url 'client_status_list' %}" class="btn btn-outline-secondary">Cancel</a>
  </div>
{% endblock %}

CRM/templates/delete_property.html
<!-- delete_event.html -->
{% extends 'base_event.html' %}

{% block title %}Estates Solutions | Delete Property{% endblock %}

{% block content %}
<h2 class="mb-4 container-header">Delete Property</h2>
<div class="col-md-6 container-content">
    <p>Are you sure you want to delete the property "{{ property }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Property</button>
    </form>
    <a href="#" class="btn btn-outline-secondary mt-3" onclick="goBack()">Cancel</a>
</div>
<script>
    function goBack() {
        window.history.back();
    }
    </script>
{% endblock %}

CRM/templates/edit_event.html
<!-- edit_event.html -->
{% extends 'base_event.html' %}

{% block title %}Estates Solutions | Edit Event{% endblock %}
{% block content %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<h2 class="mb-4 container-header">Edit Event</h2>
<div class="col-md-12 container-content">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="form-group">
                    {{ form.event_type.label_tag }}
                    {{ form.event_type|add_class:"form-control"   }}
                    {% for error in form.event_type.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                
                <script>
                    // Assuming you have included jQuery
                    $(document).ready(function() {
                        // Create the "Add Event Type" option
                        var addEventTypeOption = $('<option>', {
                            value: 'add_event_type',
                            text: 'Add Event Type'
                        });
                        addEventTypeOption.css('color', 'grey');
                        // Append the option to the select element
                        $('#id_event_type').append(addEventTypeOption);
                
                        // Handle change event
                        $('#id_event_type').change(function() {
                            var selectedValue = $(this).val();
                            if (selectedValue === 'add_event_type') {
                                // Get the URL for 'add_event_type' using Django's URL template tag
                                var addEventTypeUrl = "{% url 'add_event_type' %}";
                                window.location.href = addEventTypeUrl;
                            }
                        });
                    });
                </script>
                <div class="form-group">
                    {{ form.event_date.label_tag }}
                    {{ form.event_date|add_class:"form-control"   }}
                    {% for error in form.event_date.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <style>
                    #hour .options {
                        margin: 0 auto;
                    }
                    #hour .select {
                        margin: 0 auto;
                        text-align: center;
                    }
                </style>
                <div class="row" id="hour">
                    <div class="form-group col-md-4">
                        <label for="id_event_hour">Hour</label>
                        {{ form.event_hour|add_class:"form-control"   }}
                        {% for error in form.event_hour.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="id_event_minute">Minute</label>
                        {{ form.event_minute|add_class:"form-control"   }}
                        {% for error in form.event_minute.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="id_event_ampm">AM/PM</label>
                        {{ form.event_ampm|add_class:"form-control"   }}
                        {% for error in form.event_ampm.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_participant_buyer">Buyer:</label>
                    {{ form.participant_buyer|add_class:"form-control"   }}
                    {% for error in form.participant_buyer.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label for="id_participant_buyer">Owner:</label>
                    {{ form.participant_owner|add_class:"form-control"   }}
                    {% for error in form.participant_owner.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ form.participant_property.label_tag }}
                    {{ form.participant_property|add_class:"form-control"   }}
                    {% for error in form.participant_property.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group" style="padding: 0;">
                    {{ form.event_description.label_tag }}
                    {{ form.event_description|add_class:"form-control"   }}
                    {% for error in form.event_description.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-outline-primary" style="width : 100%; margin-top: 10px ">Save</button>
                <button onclick="goBack()" class="btn btn-outline-secondary" style="width : 100%; margin-top: 10px ">Back</button>
            </div>
            
        </div>
    </form>
</div>

<script>
function goBack() {
    window.history.back();
}
</script>

<style>
    /* Custom CSS for Select2 dropdown items */
    .custom-select2-dropdown .select2-selection__rendered {
        font-size: 1rem;
        font-weight: 400;
    }

</style>

<script>
    // Initialize Select2 with the custom class
    $('#id_participant_buyer').select2({
        width : '100%'
    });

    $('#id_participant_owner').select2({
        width : '100%'
    });

    $('#id_participant_property').select2({
        width : '100%'
    });
</script>

{% endblock %}

CRM/templates/events_by_property.html
<!-- events_by_property.html -->
{% extends 'base_event.html' %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

{% block title %}Estates Solutions | Events by Property{% endblock %}

{% block content %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<!-- Add this script at the bottom of your HTML file -->
<script>
    // Use jQuery.noConflict() to avoid conflicts with other libraries
    function confirmDelete(eventId) {
    const isConfirmed = window.confirm('Are you sure you want to delete this event?');

    if (isConfirmed) {
        fetch(`/crm/events/delete/${eventId}/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}',
            },
            // Additional options like body for POST requests can be added here
        })
        .then(response => response.json())
        .then(data => {
            alert(data.message);
            location.reload();
        })
        .catch(error => {
            alert('Error deleting event.');
        });
    }
}
</script>

<div class="row">
    <div class="col-md-12">
        <h2 class="mb-4">Events by Property</h2>
    </div>

    {% for property_data in events_by_property %}
        <div class="col-md-12 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <h5 class="card-title">{{ property_data.property.address }}</h5>
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#propertyEvents{{ forloop.counter }}" aria-expanded="false" aria-controls="propertyEvents{{ forloop.counter }}">
                                View Events
                            </button>
                        </div>
                        <div class="col-md-8">
                            <!-- Property Details -->
                            <div class="row">
                                <div class="col-md-6">
                                    <h5>Property Details</h5>
                                    <p>Room number: {{ property_data.property.total_rooms }}</p>
                                    <p>Bedrooms: {{ property_data.property.bedrooms }}</p>
                                    <p>Toilets: {{ property_data.property.toilets }}</p>
                                </div>
                                <div class="col-md-6">
                                    <p>Square Meter: {{ property_data.property.sqr_meter }}</p>
                                    {% if property_data.property.price_sqrm and property_data.property.price_sqrm > 0 %}
                                        <p>Price per Square Meter: {{ property_data.property.price_sqrm }}</p>
                                    {% elif property_data.property.price_month and property_data.property.price_month > 0 %}
                                        <p>Monthly Price: {{ property_data.property.price_month }}</p>
                                    {% else %}
                                        <p>No Price Information Available</p>
                                    {% endif %}
                                    <p>Bedrooms: {{ property_data.property.bedrooms }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!-- View Events Section -->
                    <div class="col-md-12 mt-2">
                        <div class="collapse" id="propertyEvents{{ forloop.counter }}">
                            <div class="list-group overflow-auto" style="max-height: 300px;">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Type</th>
                                            <th>Buyer</th>
                                            <th>Owner</th>
                                            <th>Date</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for event in property_data.events %}
                                            <tr>
                                                <td>{{ event.get_event_type_display }}</td>
                                                <td>{{ event.participant_buyer.client_name }} ({{ event.participant_buyer.phone_number }})</td>
                                                <td>{{ event.participant_owner.client_name }} ({{ event.participant_owner.phone_number }})</td>
                                                <td>{{ event.event_date }}</td>
                                                <td>
                                                    <a href="{% url 'edit_event' event.id %}" class="btn btn-sm btn-outline-primary">
                                                        <span class="material-icons">edit</span>
                                                    </a>
                                                    <a href="#" class="btn btn-sm btn-danger" onclick="confirmDelete('{{ event.id }}')">
                                                        <span class="material-icons">delete</span>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

CRM/templates/notifications.html
{% for notification in notifications %}
    <div>
        <p>{{ notification.message }}</p>
        <small>{{ notification.timestamp }}</small>
    </div>
{% endfor %}