CRM/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.EventsListView.as_view(), name='dashboard'),
    path('ajax-search/', views.ajax_search, name='ajax_search'),
    path('notifications/', views.notifications, name='notifications'),
    path('mark-notification-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('mark-all-notifications-as-read/', views.mark_all_notifications_as_read, name='mark_all_notifications_as_read'),
    path('create_client/', views.create_client, name='create_client'),
    path('events_list/', views.EventsListView.as_view(), name='events_list'),
    path('get_locations/', views.GetLocationsView.as_view(), name='get_locations'),
    path('get_properties/', views.GetProperties.as_view(), name='get_properties'),
    path('get_event_types/', views.GetEventTypes.as_view(), name='get_event_types'),
    path('get_clients/', views.GetClients.as_view(), name='get_clients'),
    path('get_events/', views.get_events, name='get_events'),
    path('add_property/', views.add_property, name='add_property'),
    path('add_rental_property/', views.add_rental_property, name='add_rental_property'),
    path('events/add/', views.add_event, name='add_event'),
    path('events/edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('events/delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('events/toggle_complete/<int:event_id>/', views.toggle_complete, name='toggle_complete'),
    path('events/add_event_type/', views.add_event_type, name='add_event_type'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/<int:client_id>/', views.client_events, name='client_events'),
    path('clients/edit/<int:client_id>/', views.edit_client, name='edit_client'),
    path('clients/delete/<int:client_id>/', views.delete_client, name='delete_client'),
    path('clients/add_notes/<int:client_id>/', views.add_client_notes, name='add_client_notes'),
    path('clients/update_suggestion/', views.suggest_property, name='update_suggestion'),
    path('events/delete_notes/<int:note_id>/<int:client_id>/', views.delete_client_note, name='delete_notes'),
    path('properties/', views.properties_list, name='properties_list'),
    path('properties/<int:property_id>/', views.property_events, name='property_events'),
    path('properties/edit/<int:property_id>/', views.edit_property, name='edit_property'),
    path('properties/delete/<int:property_id>/', views.delete_property, name='delete_property'),
    path('search/', views.search_page, name='search_page'),
    path('google-maps-script/', views.google_maps_proxy, name='google_maps_proxy'),
    path('delete_image/<int:photo_id>/', views.delete_image, name='delete_image'),
    
    path('settings_page/',views.settings_page, name='settings'),
    path('settings_page/google-authenticate/', views.google_authenticate, name='google_authenticate'),
    path('settings_page/google-authenticate-callback/', views.google_authenticate_callback, name='google_authenticate_callback'),
    path('settings_page/import-google-contacts/', views.import_google_contacts, name='import_google_contacts'),
    path('settings_page/event_types_list/', views.event_types_list, name='event_types_list'),
    path('settings_page/edit_event_type/<int:event_type_id>/', views.edit_event_type, name='edit_event_type'),
    path('settings_page/delete_event_type/<int:event_type_id>/', views.delete_event_type, name='delete_event_type'),
    path('settings_page/client_status_list/', views.client_status_list, name='client_status_list'),
    path('settings_page/edit_client_status/<int:client_status_id>/', views.edit_client_status, name='edit_client_status'),
    path('settings_page/add_client_status/', views.add_client_status, name='add_client_status'),
    path('settings_page/delete_client_status/<int:client_status_id>/', views.delete_client_status, name='delete_client_status'),
    path('settings_page/property_status_list/', views.property_status_list, name='property_status_list'),
    path('settings_page/edit_property_status/<int:property_status_id>/', views.edit_property_status, name='edit_property_status'),
    path('settings_page/add_property_status/', views.add_property_status, name='add_property_status'),
    path('settings_page/delete_property_status/<int:property_status_id>/', views.delete_property_status, name='delete_property_status'),
    path('settings_page/property_type_list/', views.property_type_list, name='property_type_list'),
    path('settings_page/edit_property_type/<int:property_type_id>/', views.edit_property_type, name='edit_property_type'),
    path('settings_page/add_property_type/', views.add_property_type, name='add_property_type'),
    path('settings_page/delete_property_type/<int:property_type_id>/', views.delete_property_type, name='delete_property_type'),
    path('settings_page/property_deal_type_list/', views.property_deal_type_list, name='property_deal_type_list'),
    path('settings_page/edit_property_deal_type/<int:property_deal_type_id>/', views.edit_property_deal_type, name='edit_property_deal_type'),
    path('settings_page/add_property_deal_type/', views.add_property_deal_type, name='add_property_deal_type'),
    path('settings_page/delete_property_deal_type/<int:property_deal_type_id>/', views.delete_property_deal_type, name='delete_property_deal_type'),
    path('settings_page/suggestions_link_settings/', views.suggestions_link_settings_page, name='suggestions_link_settings'),
    path('settings_page/profile/', views.profile, name='profile'),
    path('settings_page/products', views.products, name = 'subscriptions'),
    path('settings_page/checkout', views.checkout_monthly, name = 'checkout_monthly'),
    path('settings_page/checkout_yearly', views.checkout_yearly, name = 'checkout_yearly'),
    path('settings_page/subscriptions/succeeded', views.payment_successful, name = 'payment_successful'),
    path('settings_page/subscriptions/succeeded_y', views.payment_successful_yearly, name = 'payment_successful_yearly'),
    path('settings_page/subscriptions/cancelled', views.payment_cancelled, name = 'payment_cancelled'),
]

accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import register, user_login, user_logout,privacy_policy,terms_of_service


app_name = 'accounts' 

urlpatterns = [
    path('', user_login, name='login'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('privacy_policy/', privacy_policy, name='privacy_policy'),
    path('terms_of_service/', terms_of_service, name='terms_of_service'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import user_login
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/',include('CRM.urls')),
    path('card/', include('suggest_properties.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', user_login, name='user_login'),
    
    path('reset_password/', 
        auth_views.PasswordResetView.as_view(
             template_name = 'reset_password.html'), 
            name='reset_password'),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'reset_password_sent.html'), 
            name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'reset.html'), 
            name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'password_reset_complete.html'), 
            name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from phonenumbers import parse, PhoneNumberFormat
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone_number = PhoneNumberField(null=True, blank=True, unique=False)
    active = models.BooleanField(default = False)
    facebook_url = models.URLField(null=True, blank=True)
    instagram_url = models.URLField(null=True, blank=True)
    linkedin_url = models.URLField(null=True, blank=True)
    twitter_url = models.URLField(null=True, blank=True)
    ending_date = models.DateField(null=True, blank=True)
    # Add other fields as needed

    def __str__(self):
        return self.username
    
    
class UserPayment(models.Model):
    app_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    payment_bool = models.BooleanField(default=False)
    stripe_checkout_id = models.CharField(max_length=500)
    subscription_start_date = models.DateField(null=True, blank=True)
    subscription_end_date = models.DateField(null=True, blank=True)

accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from .models import CustomUser
from phonenumber_field.formfields import PhoneNumberField

class CustomUserCreationForm(UserCreationForm):
    phone_number = PhoneNumberField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Phone Number'}))
    accept_policies = forms.BooleanField(label='I accept the Privacy Policy and Terms of Service', required=True)
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'phone_number', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
        }
    
class CustomAuthenticationForm(AuthenticationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'password','remember_me']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        }

class CustomUserChangeForm(UserChangeForm):
    phone_number = PhoneNumberField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Phone Number'}), required=False)
    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ['username', 'email', 'phone_number','instagram_url'
                    ,'facebook_url'
                    ,'twitter_url'
                    ,'linkedin_url']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone Number'}),
        }

class CustomUserPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = CustomUser

accounts/views.py
# accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect, HttpResponse
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from CRM.models import event_type_model, client_status_types
from Realtor.models import property_status, property_type
from django.core.mail import send_mail


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['accept_policies']:
                user_instance = form.save(commit=False)
                user_instance.region = request.POST.get('region')
                user_instance.save()

                # Authenticate the user using django-allauth's authentication backend
                user = authenticate(request, username=user_instance.username, password=request.POST.get('password1'), backend='allauth.account.auth_backends.AuthenticationBackend')
                if user is not None:
                    login(request, user)
                    return redirect('accounts:login') 
                else:
                    # Handle authentication failure
                    pass
            else:
                # Handle case where policies are not accepted
                return HttpResponse("You must accept the Privacy Policy and Terms of Service.")
        else: 
            print(form.errors)
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})

import django.utils.timezone
def user_login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            success_url = reverse_lazy('dashboard')
            return redirect(success_url) 
        else:
            print(form.errors)
    else:
        form = CustomAuthenticationForm()
    return render(request, 'login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('accounts:login')

def privacy_policy(request):
    return render(request,'privacy_policy.html')

def terms_of_service(request):

    return render(request,'terms_of_service.html')

accounts/templates/base_account.html
<!-- accounts/templates/accounts/base_account.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Account{% endblock %}</title>
    <link rel="shortcut icon" href="/static/image/Picture5.png" type="x-icon">
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Add your custom styles if needed -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap');
        :root{
            --color-background-rgba: rgba(255, 255, 255, 1) ;      /* White background */
            --color-text-rgba: rgba(26, 26, 26, 1) ;               /* Dark text */
            --border-color-rgba: rgba(204, 204, 204, 1)  ;   
            --header-color-rgba: rgba(250, 250, 250, 1);       /* Light border color */
            --color-stripe-rgba: rgba(240, 240, 240, 1);
        }
        .dark-mode-variables{
            --color-background-rgba: rgba(26, 26, 26, 1) ;
            --color-text-rgba: rgba(255, 255, 255, 1) ;
            --border-color-rgba: rgba(43, 43, 43, 1) ; 
            --header-color-rgba: rgba(50, 50, 50, 1)    ;
            --color-stripe-rgba: rgba(40, 40, 40, 1);
        }
        
        body {
            font-family: 'Open Sans', sans-serif;
            display: flex;
            justify-content: space-between;
            flex-direction: column;
            overflow: hidden;
            background-color: var(--color-background-rgba) !important;
            color: var(--color-text-rgba);
            border: 1px solid var(--border-color-rgba);
        }
        /* Add your custom styles here */
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: var(--color-background-rgba);
        }
        h1, h2, label{
            color: var(--color-text-rgba);
        }
        input{
            background-color: var(--color-background-rgba) !important;
        }
        input{
            color: var(--color-text-rgba) !important;
        }
        input:focus{
            color: var(--color-text-rgba) !important;
        }
        .btn-primary{
            background-color: var(--color-text-rgba);
            color: var(--color-background-rgba);
            border:  var(--color-text-rgba) solid 1px;
        }
        .btn-primary{
            background-color: var(--color-text-rgba);
            color: var(--color-background-rgba);
            border:  var(--color-text-rgba) solid 1px;
        }
        .btn-outline-primary{
            background-color: transparent;
            color: var(--color-text-rgba);
            border:  var(--color-text-rgba) solid 1px;
        }
        .btn-outline-info{
            background-color: transparent;
            color: var(--color-text-rgba);
            border:  var(--color-text-rgba) solid 1px;
        }

        .container {
            width: 100%;
        }
        .toggle-button {
            background: none;
            border: none;
            cursor: pointer;
            padding: 0;
            font-size: 24px; /* Adjust the font size as needed */
            width: 50px;
            right: 60px;
            position: fixed;
            top: 12px;
        }

        .toggle-button .material-icons {
            color: var(--color-text-rgba);
        }

        .toggle-button .material-icons:hover {
            color: #656565;
        }

        .toggle-button:focus{
            outline: none;
        }

        .toggle-button .dark-mode-variables .material-icons {
            color: #656565; /* Dark mode color for Material Icons */
        }
        @media (max-width: 767px) {
            #title h1{
                font-size: 1.5rem;
                line-height: 0;
            }
            #title h2{
                font-size: 1.2rem;
            }
            .toggle-button{
                right: 10px;
                top: 20px;
            }
        }
        
    </style>
</head>
<body class="{% if isDarkMode %}dark-mode-variables{% endif %}">

<div class="container mt-5">
    <div style="top: 30px; left: 30px; position: absolute;" id="title">
        <h1>Estates.</h1>
        <h2>Solutions</h2>
    </div>
    <button class="toggle-button" onclick="toggleDarkMode()">
        <i id="modeIcon" class="material-icons">brightness_4</i> <!-- Google Material Icon sun icon -->
    </button>
    <div class="row justify-content-center">
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

<!-- Include Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    // JavaScript to toggle dark mode and remember user preference
    function toggleDarkMode() {
        const rootElement = document.documentElement;
        const isDarkMode = rootElement.classList.toggle('dark-mode-variables');

        // Update the icon based on the dark mode state
        const modeIcon = document.getElementById('modeIcon');
        modeIcon.textContent = isDarkMode ? 'brightness_7' : 'brightness_4';

        // Store user preference in localStorage as a string
        localStorage.setItem('darkMode', isDarkMode.toString());
    }

    // Check if the user had a dark mode preference and apply it on page load
    document.addEventListener('DOMContentLoaded', () => {
        const storedMode = localStorage.getItem('darkMode');
        const isDarkMode = storedMode === 'true';

        // Apply dark mode and update the icon
        const rootElement = document.documentElement;
        const modeIcon = document.getElementById('modeIcon');

        if (isDarkMode) {
            rootElement.classList.add('dark-mode-variables');
            modeIcon.textContent = 'brightness_7';
        }
    });
    
</script>
</body>
</html>

accounts/templates/login.html
<!-- accounts/templates/accounts/login.html -->

{% extends 'base_account.html' %}

{% block title %}Login{% endblock %}
{% load socialaccount %}
{% load widget_tweaks %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="container">
    <h2 style="text-align: center;">Login</h2>
    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username|add_class:"form-control" }}
            {% for error in form.username.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.password.label_tag }}
            <div class="input-group" style="width: 100%;">
                {{ form.password|add_class:"form-control"  }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('{{ form.password.id_for_label }}')">
                        <i id="passwordToggleIcon" class="fa fa-eye-slash"></i>
                    </button>
                </div>
            </div>
            {% for error in form.password.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        
        <!-- Display non-field errors -->
        <div class="form-group" style="max-width: 300px;">
            {% for error in form.non_field_errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <div style="margin-bottom: 5px">
            <a  href="{% url 'reset_password' %}">Forgot password?</a>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 100%;  margin-bottom: 10px;">Login</button>
        
        <a href="{% url 'accounts:register' %}" style="width: 100%; ">
            <button type="button" class="btn btn-outline-primary" style="width: 100%; margin-bottom: 10px;" >Register</button>
        </a>
        
        <div class="form-group">
            <a href="{% provider_login_url 'google' %}">
                <button type="button" class="btn btn-outline-info" style="width: 100%;">
                    <i class="fa-brands fa-google"></i>
                    Sign in with Google
                </button>
            </a>
        </div>
        
    </form>

    <!-- JavaScript to toggle password visibility -->
    <script>
        function togglePassword(inputId) {
            var passwordInput = document.getElementById(inputId);
            var passwordToggleIcon = document.getElementById('passwordToggleIcon');
            if (passwordInput.type === 'password') {
                passwordInput.type = 'text';
                passwordToggleIcon.classList.remove('fa-eye-slash');
                passwordToggleIcon.classList.add('fa-eye');
            } else {
                passwordInput.type = 'password';
                passwordToggleIcon.classList.remove('fa-eye');
                passwordToggleIcon.classList.add('fa-eye-slash');
            }
        }
    </script>
</div>
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends 'base_account.html' %}

{% block title %}Reset Complete{% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="container" style="width: 80vw;">
    <h3>Password reset complete</h3>

    <p>Your password has been set. You may go ahead and log in now.</p>
    <a href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock %}

accounts/templates/register.html
<!-- accounts/templates/accounts/register.html -->
{% extends 'base_account.html' %}

{% block title %}Register{% endblock %}
{% load widget_tweaks %}
{% load socialaccount %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://unpkg.com/htmx.org@1.9.2"></script>
<style>
    @media (max-width: 767px) {
        form{
            width: 70vw;
        }
    }
</style>
<h2 style="text-align: center;">Register</h2>
    <form method="post" >
        {% csrf_token %}

        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
            {% for error in form.username.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.firstname.label_tag }}
            {{ form.firstname }}
        </div>
        <div class="form-group">
            {{ form.lastname.label_tag }}
            {{ form.lastname }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}
            {{ form.email }}
            {% for error in form.email.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        
        <div class="form-group">
            {{ form.country.label_tag }}
            {{ form.country }}
        </div>
        <div class="form-group">
            {{ form.region.label_tag }}
            {{ form.region }}
        </div>
        
        <div class="form-group">
            {{ form.phone_number.label_tag }}
            {{ form.phone_number }}
            {% for error in form.phone_number.errors %}
                <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        
        <div class="form-group" style="width: 100%;">
            {{ form.password1.label_tag }}
            <div class="input-group" style="width: 100%;">
                {{ form.password1|add_class:"form-control" }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('{{ form.password1.id_for_label }}')">
                        <i class="fa fa-eye-slash"></i>
                    </button>
                </div>
            </div>
        </div>
        
        <div class="form-group">
            {{ form.password2.label_tag }}
            <div class="input-group">
                {{ form.password2|add_class:"form-control" }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('{{ form.password2.id_for_label }}')">
                        <i class="fa fa-eye-slash"></i>
                    </button>
                </div>
            </div>
            {% for error in form.password2.errors %}
                <div class="invalid-feedback" style="display: block;">{{ error }}</div>
            {% endfor %}
        </div>
        
        <input type="checkbox" id="accept_policies" name="accept_policies">
        <label for="accept_policies">I accept the <a href="{% url 'accounts:privacy_policy' %}">Privacy Policy</a> and <a href="{% url 'accounts:terms_of_service' %}">Terms of Service</a></label><br>
        {% if request.method == "POST" and not form.accept_policies.value %}
            <p style="width: 100%; max-width: 350px;" class="text-danger" >Please accept our Privacy Policy and Terms of Service to proceed with registration.</p>
        {% endif %}
        <button type="submit" class="btn btn-primary" style="width: 100%; margin-bottom: 10px;">Register</button>
        <a href="{% url 'accounts:login' %}" style="width: 100%; ">
            <button type="button" class="btn btn-outline-primary" style="width: 100%; margin-bottom: 10px;" >Login</button>
        </a>
        <div class="form-group">
            <a href="{% provider_login_url 'google' %}">
                <button type="button" class="btn btn-outline-info" style="width: 100%;">
                    <i class="fa-brands fa-google"></i>
                    Sign up with Google
                </button>
            </a>
        </div>
    </form>
    

    <!-- JavaScript to toggle password visibility -->
    <script>
        function togglePassword(inputId) {
            var passwordInput = document.getElementById(inputId);
            passwordInput.type = passwordInput.type === 'password' ? 'text' : 'password';
        }
    </script>
    
{% endblock %}

accounts/templates/reset.html
{% extends 'base_account.html' %}

{% block title %}Password reset confirm{% endblock %}
{% load widget_tweaks %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<div class="container" style="width: 80vw;">
    <h3>Enter new password</h3>

    <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
    <form class="form" method="POST">
        {% csrf_token %}
        <div class="form-group" style="width: 100%;">
            {{ form.new_password1.label_tag }}
            <div class="input-group" style="width: 100%;">
                {{ form.new_password1|add_class:"form-control" }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('{{ form.new_password1.id_for_label }}')">
                        <i class="fa fa-eye-slash"></i>
                    </button>
                </div>
            </div>
        </div>
        
        <div class="form-group">
            {{ form.new_password2.label_tag }}
            <div class="input-group">
                {{ form.new_password2|add_class:"form-control" }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePassword('{{ form.new_password2.id_for_label }}')">
                        <i class="fa fa-eye-slash"></i>
                    </button>
                </div>
            </div>
            {% for error in form.new_password2.errors %}
                <div class="invalid-feedback" style="display: block;">{{ error }}</div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-outline-primary" style="width: 100%; margin-top: 20px; margin-bottom: 10px; ">Change my password</button>
    </form>
    <!-- JavaScript to toggle password visibility -->
    <script>
        function togglePassword(inputId) {
            var passwordInput = document.getElementById(inputId);
            passwordInput.type = passwordInput.type === 'password' ? 'text' : 'password';
        }
    </script>
</div>
{% endblock %}